version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.10.2-buster

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Install PyInstaller
          command: pip install pyinstaller

      - run:
          name: Install pytest
          command: pip install pytest

      - run:
          name: Build splitter executable
          command: pyinstaller gui-splitter.py --onefile
          working_directory: ./gui

      - run:
          name: Build merger executable
          command: pyinstaller gui-merger.py --onefile
          working_directory: ./gui

      - run:
          name: Run tests
          command: pytest

workflows:
  build-and-test:
    jobs:
      - build-and-test
