name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build splitter executable
        run: pyinstaller gui-splitter.py --onefile

      - name: Build merger executable
        run: pyinstaller gui-merger.py --onefile

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false

      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: Executables
          path: |
            ./dist/gui-splitter.exe
            ./dist/gui-merger.exe

      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=release_id::${{ steps.create_release.outputs.id }}"

      - name: Upload Artifacts to Release
        uses: actions/upload-artifact@v2
        with:
          name: Executables
          path: |
            ./dist/gui-splitter.exe
            ./dist/gui-merger.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ steps.get_release_id.outputs.release_id }}
